[package]
name = "wrapper"
version = "0.1.0"
authors = ["Martin Pinholt <mapi@itu.dk>"]
edition = "2018"

[dependencies]
nalgebra = "0.19"
anyhow = "1.0.26"
gl = "0.14.0"

[lib]
name = "wrapper"
path = "src/lib.rs"